# Generated by Django 4.2.27 on 2026-01-30 02:24

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='О нас')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='ФИО')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('exp', models.CharField(max_length=50, verbose_name='Опыт')),
            ],
            options={
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название соцсети')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка на аккаунт')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.employee')),
            ],
            options={
                'verbose_name_plural': 'Соцсети сотрудников',
            },
        ),
    ]
