# Generated by Django 4.2.27 on 2026-02-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_employee_options_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
