# Generated by Django 4.2.27 on 2026-02-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название страницы')),
                ('phone_number1', models.CharField(help_text='+996 707 555 444', max_length=20, verbose_name='Номер телефона №1')),
                ('phone_number2', models.CharField(blank=True, help_text='+996 507 555 444', max_length=20, null=True, verbose_name='Номер телефона №2')),
                ('phone_number3', models.CharField(blank=True, help_text='+996 222 555 444', max_length=20, null=True, verbose_name='Номер телефона №3')),
                ('map', models.TextField(verbose_name='Ссылка на карту')),
                ('time_to_work', models.CharField(blank=True, help_text='c 08:00 до 17:00', max_length=100, null=True, verbose_name='Время работы')),
                ('social_instagram', models.CharField(blank=True, help_text='https://www.instagram.com/edzen_bey/', max_length=255, null=True, verbose_name='Ссылка на instagram')),
                ('social_telegram', models.CharField(blank=True, help_text='https://t.me/edzenDev', max_length=255, null=True, verbose_name='Ссылка на telegram')),
                ('social_whatsapp', models.CharField(blank=True, help_text='https://wa.me/996703016683/', max_length=255, null=True, verbose_name='Ссылка на whatsapp')),
                ('social_facebook', models.CharField(blank=True, help_text='https://www.facebook.com/groups/feed/', max_length=255, null=True, verbose_name='Ссылка на facebook')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
